version: '3.1'
services:
#  node:
#    image: "node:19-bullseye"
#    user: "node"
#    working_dir: /home/node/app
#    environment:
#      - NODE_ENV=production
#    volumes:
#      - ./:/home/node/app
#    ports:
#      - "8888:8888"
#    command: "npm start"

  postgresql:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: raj
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
     - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE= 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    hostname: mongodb
    volumes:
      - mongo:/data/db
#      - mongoconfig:/data/configdb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME:raja
      - MONGO_INITDB_ROOT_PASSWORD:admin
    networks:
      - mongodb_network

  mongo-express:
    container_name: mongo_express
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=raja
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mongodb_network
    depends_on:
      - mongodb

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  microservices-net:
    driver: bridge
  mongodb_network:
    driver: bridge
    name: mongo-network
volumes:
  postgres:
  pgadmin:
  mongo: